### ISSUE TITLE
Error FILE_PART_EMPTY (caused by upload.SaveFilePart)

### ISSUE THREAD

**Issue by JoaGamo** [TheodoreKrypton/tgfs#25]
Hello, I've got a problem trying to execute the program.
My steps were:
Brand new debian 12 Virtual Machine -> install npm and usual packages -> clone this repo and configure in config.yaml everything -> install with npm install tgfs

I tried to run the program with 'npm exec' then doing 'tgfs -w' but it fails with the error in the title
```
[ERROR] error encountered in uploading worker 1: RPCError: 400: FILE_PART_EMPTY (caused by upload.SaveFilePart) retries left: 1
/root/tgfs/node_modules/tgfs/dist/src/api/client/message-api/file-uploader.js:124
            throw new base_1.AggregatedError(this.errors);
                  ^

AggregatedError: 400: FILE_PART_EMPTY (caused by upload.SaveFilePart)
400: FILE_PART_EMPTY (caused by upload.SaveFilePart)
    at UploaderFromBuffer.send (/root/tgfs/node_modules/tgfs/dist/src/api/client/message-api/file-uploader.js:124:19)
    at _send (/root/tgfs/node_modules/tgfs/dist/src/api/client/message-api/api.js:98:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.sendFile (/root/tgfs/node_modules/tgfs/dist/src/api/client/message-api/api.js:117:16)
    at async Client.updateMetadata (/root/tgfs/node_modules/tgfs/dist/src/api/client/metadata-api.js:39:31)
    at async Client.syncMetadata (/root/tgfs/node_modules/tgfs/dist/src/api/client/metadata-api.js:31:9)
    at async Client.createRootDirectory (/root/tgfs/node_modules/tgfs/dist/src/api/client/directory-api.js:10:9)
    at async Client.init (/root/tgfs/node_modules/tgfs/dist/src/api/client/index.js:20:13)
    at async createClient (/root/tgfs/node_modules/tgfs/dist/src/api/client/index.js:12:5)
    at async /root/tgfs/node_modules/tgfs/dist/src/index.js:49:20 {
  errors: [
    RPCError: 400: FILE_PART_EMPTY (caused by upload.SaveFilePart)
        at RPCMessageToError (/root/tgfs/node_modules/telegram/errors/index.js:28:12)
        at MTProtoSender._handleRPCResult (/root/tgfs/node_modules/telegram/network/MTProtoSender.js:546:58)
        at MTProtoSender._processMessage (/root/tgfs/node_modules/telegram/network/MTProtoSender.js:476:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async MTProtoSender._recvLoop (/root/tgfs/node_modules/telegram/network/MTProtoSender.js:424:17) {
      code: 400,
      errorMessage: 'FILE_PART_EMPTY'
    },
    RPCError: 400: FILE_PART_EMPTY (caused by upload.SaveFilePart)
        at RPCMessageToError (/root/tgfs/node_modules/telegram/errors/index.js:28:12)
        at MTProtoSender._handleRPCResult (/root/tgfs/node_modules/telegram/network/MTProtoSender.js:546:58)
        at MTProtoSender._processMessage (/root/tgfs/node_modules/telegram/network/MTProtoSender.js:476:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async MTProtoSender._recvLoop (/root/tgfs/node_modules/telegram/network/MTProtoSender.js:424:17) {
      code: 400,
      errorMessage: 'FILE_PART_EMPTY'
    }
  ]
}
```

**Comment by fatshotty** [comment]
same here

**Comment by TheodoreKrypton** [comment]
Hi just published a new commit, please let me know if it works now
