### ISSUE TITLE
"create directory" not works

### ISSUE THREAD

**Issue by fatshotty** [TheodoreKrypton/tgfs#27]
here is log about creating folder via WebDav.
It seems folder has been created, but i found error in the log

```
[2024-04-22T11:49:57.370] [INFO] OPTIONS /
[2024-04-22T11:49:57.371] [INFO] OPTIONS 200
[2024-04-22T11:49:57.373] [INFO] PROPFIND /
[2024-04-22T11:49:57.374] [INFO] PROPFIND 207
[2024-04-22T11:49:57.376] [ERROR] FILE_OR_DIR_DOES_NOT_EXIST /untitled folder No such file or directory: /untitled folder
/untitled folder: No such file or directory: /untitled folder
    at /Users/fatshotty/Sites/tgfs/dist/src/api/ops/list.js:23:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/fatshotty/Sites/tgfs/dist/src/server/webdav/tgfs-filesystem.js:147:29
[2024-04-22T11:49:57.376] [INFO] MKCOL /untitled%20folder
[2024-04-22T11:49:57.529] [INFO] - [Starting indirect file download in chunks of 524288 at 0, stride 5242880]
[2024-04-22T11:49:57.533] [INFO] - [Connecting to 149.154.167.92:443/TCPFull...]
[2024-04-22T11:49:57.582] [INFO] - [Connection to 149.154.167.92:443/TCPFull complete!]
[2024-04-22T11:49:57.806] [INFO] MKCOL 201
[2024-04-22T11:50:04.314] [INFO] OPTIONS /
[2024-04-22T11:50:04.314] [INFO] OPTIONS 200
[2024-04-22T11:50:04.320] [INFO] PROPFIND /
[2024-04-22T11:50:04.322] [INFO] PROPFIND 207
[2024-04-22T11:50:04.326] [INFO] MOVE /untitled%20folder
[2024-04-22T11:50:04.506] [INFO] - [Starting indirect file download in chunks of 524288 at 0, stride 5242880]
[2024-04-22T11:50:04.898] [INFO] - [Starting indirect file download in chunks of 524288 at 0, stride 5242880]
[2024-04-22T11:50:05.116] [ERROR] FILE_OR_DIR_DOES_NOT_EXIST /untitled folder No such file or directory: /untitled folder
/untitled folder: No such file or directory: /untitled folder
    at /Users/fatshotty/Sites/tgfs/dist/src/api/ops/list.js:23:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/fatshotty/Sites/tgfs/dist/src/server/webdav/tgfs-filesystem.js:147:29
[2024-04-22T11:50:05.116] [INFO] MOVE 201
```

after that
trying to upload file via webdav, got the same error:

```
[2024-04-22T11:50:14.134] [ERROR] FILE_OR_DIR_DOES_NOT_EXIST /up/Photos-001.zip No such file or directory: /up/Photos-001.zip
/up/Photos-001.zip: No such file or directory: /up/Photos-001.zip
    at /Users/fatshotty/Sites/tgfs/dist/src/api/ops/list.js:23:19
    at async /Users/fatshotty/Sites/tgfs/dist/src/server/webdav/tgfs-filesystem.js:147:29
[2024-04-22T11:50:14.134] [INFO] PUT /up/Photos-001.zip
[2024-04-22T11:50:14.134] [ERROR] FILE_OR_DIR_DOES_NOT_EXIST /up/Photos-001.zip No such file or directory: /up/Photos-001.zip
/up/Photos-001.zip: No such file or directory: /up/Photos-001.zip
    at /Users/fatshotty/Sites/tgfs/dist/src/api/ops/list.js:23:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/fatshotty/Sites/tgfs/dist/src/server/webdav/tgfs-filesystem.js:147:29
[2024-04-22T11:50:14.433] [INFO] - [Starting indirect file download in chunks of 524288 at 0, stride 5242880]
[2024-04-22T11:50:15.294] [INFO] [worker 0] 5.548739231551771% uploaded
[2024-04-22T11:50:15.329] [INFO] [worker 1] 5.918655180321889% uploaded

[2024-04-22T11:50:15.329] [INFO] [worker 1] .......................................... uploaded

[2024-04-22T11:50:28.819] [INFO] PUT 201
[2024-04-22T11:50:28.825] [INFO] PROPFIND /up
[2024-04-22T11:50:28.829] [INFO] [worker 0] 100% uploaded
[2024-04-22T11:50:28.886] [INFO] [worker 3] 100% uploaded
[2024-04-22T11:50:28.943] [INFO] [worker 1] 100% uploaded
[2024-04-22T11:50:29.094] [INFO] [worker 6] 100% uploaded
[2024-04-22T11:50:29.162] [INFO] PROPFIND 207
[2024-04-22T11:50:29.177] [INFO] [worker 5] 100% uploaded
[2024-04-22T11:50:29.223] [INFO] [worker 4] 100% uploaded
[2024-04-22T11:50:29.264] [INFO] [worker 8] 100% uploaded
[2024-04-22T11:50:29.338] [INFO] [worker 9] 100% uploaded
[2024-04-22T11:50:29.364] [INFO] [worker 7] 100% uploaded
[2024-04-22T11:50:29.381] [INFO] [worker 11] 100% uploaded
[2024-04-22T11:50:29.403] [INFO] [worker 10] 100% uploaded
[2024-04-22T11:50:29.439] [INFO] [worker 13] 100% uploaded
[2024-04-22T11:50:29.472] [INFO] [worker 12] 100% uploaded
[2024-04-22T11:50:29.502] [INFO] [worker 14] 100% uploaded
[2024-04-22T11:50:29.516] [INFO] [worker 2] 100% uploaded
[2024-04-22T11:50:29.583] [ERROR] RPCError 400: FILE_PART_0_MISSING (caused by messages.SendMedia)
RPCError: 400: FILE_PART_0_MISSING (caused by messages.SendMedia)
    at RPCMessageToError (/Users/fatshotty/Sites/tgfs/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/Users/fatshotty/Sites/tgfs/node_modules/telegram/network/MTProtoSender.js:546:58)
    at MTProtoSender._processMessage (/Users/fatshotty/Sites/tgfs/node_modules/telegram/network/MTProtoSender.js:476:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (/Users/fatshotty/Sites/tgfs/node_modules/telegram/network/MTProtoSender.js:424:17)
[2024-04-22T11:50:29.583] [INFO] PUT 500
```

and file is not created :/

**Comment by TheodoreKrypton** [comment]
perhaps it's because the space in the folder name. Let me have a try to verify

**Comment by fatshotty** [comment]
I created a new folder without space. Same error.
then I tried to upload a new file and then same error :/

**Comment by TheodoreKrypton** [comment]
Hi just published a new version, please help to check if it works now

**Comment by TheodoreKrypton** [comment]
> Do u have a discord or telegram channel to discuss about that?

Just created one

https://t.me/tgfsdiscussion/3
